/**
 * Regenerated by `npm run work:filter:person` (with `work-person-filtered.json` for the color script).
 * Until you run a successful person filter, `PERSON_FILTER_APPLIED` is false and `color:group` uses
 * all files in `public/images/work/site-pull`.
 */
export const PERSON_FILTER_APPLIED = false as const;
export const PERSON_IMAGE_FILENAMES = [] as const;
