/**
 * Auto-generated by `npm run color:group` — do not edit by hand.
 * Source: public/images/work/site-pull (see work-person-filtered.json when present; full-image palette, no crop)
 * Images analyzed: 255
 * @generated 2026-04-26T21:46:16.839Z
 */

import type { WorkItem } from "./work-types";
import type { WorkColorKey } from "./work-types";

export const workColorGroups: Record<WorkColorKey, WorkItem[]> = {
  black: [
    { kind: "image" as const, src: "/images/work/site-pull/site-080.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-165.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-183.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-199.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-213.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-214.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-244.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-246.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-374.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-372.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-370.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-368.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-360.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-356.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-355.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-376.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-351.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-318.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-316.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-285.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-301.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-275.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-292.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-271.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-270.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-250.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-265.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-262.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-260.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-257.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-255.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-251.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-240.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-225.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-215.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-207.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-191.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-177.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-172.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-160.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-158.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-155.jpg" },
  ],
  white: [
    { kind: "image" as const, src: "/images/work/site-pull/site-308.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-311.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-385.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-389.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-388.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-383.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-381.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-377.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-375.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-373.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-371.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-369.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-362.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-359.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-382.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-354.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-325.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-328.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-307.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-305.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-278.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-298.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-274.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-291.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-254.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-269.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-249.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-243.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-239.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-234.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-224.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-222.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-208.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-205.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-196.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-192.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-188.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-184.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-180.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-175.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-167.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-162.jpg" },
  ],
  neutral: [
    { kind: "image" as const, src: "/images/work/site-pull/site-001.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-002.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-040.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-041.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-042.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-043.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-044.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-049.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-050.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-051.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-052.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-061.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-064.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-065.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-067.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-068.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-070.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-071.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-072.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-073.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-074.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-075.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-076.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-077.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-083.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-084.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-092.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-095.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-097.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-098.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-106.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-107.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-108.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-109.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-110.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-123.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-125.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-127.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-128.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-132.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-139.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-148.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-151.jpg" },
  ],
  warm: [
    { kind: "image" as const, src: "/images/work/site-pull/site-091.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-147.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-152.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-170.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-178.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-204.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-220.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-221.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-232.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-284.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-287.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-289.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-357.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-358.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-387.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-378.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-353.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-324.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-320.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-300.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-302.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-277.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-296.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-273.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-290.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-253.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-268.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-264.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-261.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-258.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-256.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-252.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-245.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-230.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-219.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-212.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-200.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-185.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-174.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-164.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-159.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-156.jpg" },
  ],
  cool: [
    { kind: "image" as const, src: "/images/work/site-pull/site-045.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-055.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-056.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-057.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-081.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-082.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-096.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-129.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-133.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-161.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-166.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-168.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-169.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-194.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-197.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-198.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-229.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-236.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-237.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-241.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-282.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-286.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-294.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-306.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-326.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-384.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-386.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-248.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-242.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-235.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-233.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-223.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-218.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-206.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-203.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-195.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-190.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-186.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-182.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-176.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-173.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-163.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-157.jpg" },
  ],
  vivid: [
    { kind: "image" as const, src: "/images/work/site-pull/site-003.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-004.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-046.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-047.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-054.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-058.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-059.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-060.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-062.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-079.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-089.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-090.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-102.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-103.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-104.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-105.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-111.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-112.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-113.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-114.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-115.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-116.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-117.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-119.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-121.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-122.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-124.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-126.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-130.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-131.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-134.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-136.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-137.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-138.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-140.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-141.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-143.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-144.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-145.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-149.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-150.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-153.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-154.jpg" },
  ],
};

/*
Classification log (last run):
  site-001.jpg → neutral
  site-002.jpg → neutral
  site-003.webp → vivid
  site-004.jpg → vivid
  site-040.jpg → neutral
  site-041.jpg → neutral
  site-042.jpg → neutral
  site-043.jpg → neutral
  site-044.png → neutral
  site-045.jpg → cool
  site-046.jpg → vivid
  site-047.jpg → vivid
  site-049.jpg → neutral
  site-050.jpg → neutral
  site-051.jpg → neutral
  site-052.jpg → neutral
  site-054.jpg → vivid
  site-055.jpg → cool
  site-056.jpg → cool
  site-057.jpg → cool
  site-058.jpg → vivid
  site-059.png → vivid
  site-060.png → vivid
  site-061.jpg → neutral
  site-062.jpg → vivid
  site-064.jpg → neutral
  site-065.jpg → neutral
  site-067.jpg → neutral
  site-068.jpg → neutral
  site-070.jpg → neutral
  site-071.jpg → neutral
  site-072.jpg → neutral
  site-073.jpg → neutral
  site-074.jpg → neutral
  site-075.jpg → neutral
  site-076.jpg → neutral
  site-077.jpg → neutral
  site-079.jpg → vivid
  site-080.jpg → black
  site-081.jpg → cool
  site-082.jpg → cool
  site-083.jpg → neutral
  site-084.jpg → neutral
  site-089.jpg → vivid
  site-090.jpg → vivid
  site-091.jpg → warm
  site-092.jpg → neutral
  site-095.jpg → neutral
  site-096.jpg → cool
  site-097.png → neutral
  site-098.png → neutral
  site-102.jpg → vivid
  site-103.jpg → vivid
  site-104.jpg → vivid
  site-105.jpg → vivid
  site-106.jpg → neutral
  site-107.jpg → neutral
  site-108.jpg → neutral
  site-109.jpg → neutral
  site-110.jpg → neutral
  site-111.jpg → vivid
  site-112.jpg → vivid
  site-113.jpg → vivid
  site-114.jpg → vivid
  site-115.jpg → vivid
  site-116.jpg → vivid
  site-117.jpg → vivid
  site-119.jpg → vivid
  site-121.jpg → vivid
  site-122.webp → vivid
  site-123.jpg → neutral
  site-124.jpg → vivid
  site-125.webp → neutral
  site-126.png → vivid
  site-127.png → neutral
  site-128.png → neutral
  site-129.png → cool
  site-130.png → vivid
  site-131.png → vivid
  site-132.png → neutral
  site-133.png → cool
  site-134.png → vivid
  site-136.png → vivid
  site-137.png → vivid
  site-138.png → vivid
  site-139.png → neutral
  site-140.jpg → vivid
  site-141.jpg → vivid
  site-143.jpg → vivid
  site-144.png → vivid
  site-145.jpg → vivid
  site-147.jpg → warm
  site-148.jpg → neutral
  site-149.jpg → vivid
  site-150.jpg → vivid
  site-151.jpg → neutral
  site-152.jpg → warm
  site-153.jpg → vivid
  site-154.jpg → vivid
  site-155.jpg → neutral
  site-156.jpg → neutral
  site-157.jpg → vivid
  site-158.jpg → neutral
  site-159.jpg → neutral
  site-160.jpg → neutral
  site-161.jpg → cool
  site-162.jpg → vivid
  site-163.jpg → vivid
  site-164.jpg → neutral
  site-165.jpg → black
  site-166.jpg → cool
  site-167.jpg → vivid
  site-168.jpg → cool
  site-169.jpg → cool
  site-170.png → warm
  site-172.jpg → neutral
  site-173.jpg → vivid
  site-174.png → neutral
  site-175.jpg → vivid
  site-176.jpg → vivid
  site-177.jpg → neutral
  site-178.jpg → warm
  site-180.jpg → vivid
  site-182.jpg → vivid
  site-183.jpg → black
  site-184.jpg → vivid
  site-185.jpg → neutral
  site-186.jpg → vivid
  site-188.jpg → vivid
  site-190.jpg → vivid
  site-191.jpg → neutral
  site-192.jpg → vivid
  site-194.jpg → cool
  site-195.jpg → vivid
  site-196.jpg → vivid
  site-197.jpg → cool
  site-198.jpg → cool
  site-199.jpg → black
  site-200.jpg → neutral
  site-203.jpg → vivid
  site-204.jpg → warm
  site-205.jpg → vivid
  site-206.jpg → vivid
  site-207.jpg → neutral
  site-208.jpg → vivid
  site-212.jpg → neutral
  site-213.jpg → black
  site-214.jpg → black
  site-215.jpg → neutral
  site-218.jpg → vivid
  site-219.jpg → neutral
  site-220.jpg → warm
  site-221.jpg → warm
  site-222.jpg → vivid
  site-223.png → vivid
  site-224.jpg → vivid
  site-225.jpg → neutral
  site-229.jpg → cool
  site-230.png → neutral
  site-232.jpg → warm
  site-233.jpg → vivid
  site-234.jpg → vivid
  site-235.jpg → vivid
  site-236.jpg → cool
  site-237.jpg → cool
  site-239.png → vivid
  site-240.jpg → neutral
  site-241.jpg → cool
  site-242.png → vivid
  site-243.png → vivid
  site-244.png → black
  site-245.png → neutral
  site-246.png → black
  site-248.png → vivid
  site-249.png → vivid
  site-250.png → vivid
  site-251.png → neutral
  site-252.jpg → neutral
  site-253.jpg → vivid
  site-254.jpg → vivid
  site-255.jpg → neutral
  site-256.jpg → neutral
  site-257.jpg → neutral
  site-258.jpg → neutral
  site-260.jpg → neutral
  site-261.jpg → neutral
  site-262.png → neutral
  site-264.jpg → neutral
  site-265.png → neutral
  site-268.jpg → neutral
  site-269.jpg → neutral
  site-270.jpg → neutral
  site-271.jpg → vivid
  site-273.jpg → vivid
  site-274.jpg → vivid
  site-275.jpg → vivid
  site-277.jpg → vivid
  site-278.jpg → vivid
  site-282.jpg → cool
  site-284.jpg → warm
  site-285.jpg → vivid
  site-286.jpg → cool
  site-287.jpg → warm
  site-289.jpg → warm
  site-290.jpg → neutral
  site-291.jpg → neutral
  site-292.jpg → neutral
  site-294.png → cool
  site-296.png → neutral
  site-298.png → neutral
  site-300.png → vivid
  site-301.png → neutral
  site-302.jpg → neutral
  site-305.jpg → neutral
  site-306.jpg → cool
  site-307.jpg → vivid
  site-308.png → white
  site-311.png → white
  site-316.png → neutral
  site-318.jpg → vivid
  site-320.jpg → neutral
  site-324.png → vivid
  site-325.png → vivid
  site-326.png → cool
  site-328.png → neutral
  site-351.jpg → neutral
  site-353.jpg → neutral
  site-354.jpg → neutral
  site-355.jpg → neutral
  site-356.jpg → neutral
  site-357.jpg → warm
  site-358.jpg → warm
  site-359.jpg → neutral
  site-360.jpg → neutral
  site-362.jpg → neutral
  site-368.jpg → neutral
  site-369.jpg → neutral
  site-370.jpg → neutral
  site-371.jpg → neutral
  site-372.jpg → neutral
  site-373.jpg → neutral
  site-374.jpg → neutral
  site-375.jpg → neutral
  site-376.jpg → vivid
  site-377.jpg → neutral
  site-378.jpg → vivid
  site-381.jpg → neutral
  site-382.jpg → vivid
  site-383.jpg → neutral
  site-384.jpg → cool
  site-385.jpg → white
  site-386.jpg → cool
  site-387.jpg → warm
  site-388.jpg → neutral
  site-389.jpg → neutral
*/
