/**
 * Auto-generated by `npm run color:group` — do not edit by hand.
 * Source: public/images/work/site-pull (see work-person-filtered.json when present; auto palette, no crop).
 * Curation: lib/work-curation.json → applyWorkCuration() in the app.
 * Images analyzed: 124
 * @generated 2026-04-26T23:49:10.337Z
 */

import type { WorkItem } from "./work-types";
import type { WorkColorKey } from "./work-types";

export const workColorGroups: Record<WorkColorKey, WorkItem[]> = {
  black: [
    { kind: "image" as const, src: "/images/work/site-pull/site-080.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-217.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-228.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-281.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-366.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-364.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-352.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-319.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-312.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-295.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-259.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-226.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-099.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-380.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-303.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-288.jpg" },
  ],
  white: [
    { kind: "image" as const, src: "/images/work/site-pull/site-189.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-313.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-315.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-379.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-367.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-365.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-361.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-321.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-314.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-299.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-263.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-231.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-120.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-087.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-085.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-083.jpg" },
  ],
  neutral: [
    { kind: "image" as const, src: "/images/work/site-pull/site-002.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-011.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-012.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-041.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-042.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-043.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-044.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-049.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-050.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-051.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-052.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-053.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-061.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-063.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-064.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-065.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-066.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-067.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-068.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-069.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-070.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-071.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-072.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-073.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-074.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-075.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-076.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-077.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-078.jpg" },
  ],
  warm: [
    { kind: "image" as const, src: "/images/work/site-pull/site-001.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-179.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-210.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-211.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-266.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-323.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-363.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-322.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-317.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-309.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-293.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-238.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-187.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-088.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-310.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-297.png" },
  ],
  cool: [
    { kind: "image" as const, src: "/images/work/site-pull/site-045.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-048.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-055.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-056.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-057.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-060.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-081.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-082.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-146.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-209.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-272.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-283.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-304.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-094.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-086.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-084.jpg" },
  ],
  vivid: [
    { kind: "image" as const, src: "/images/work/site-pull/site-003.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-004.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-032.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-046.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-047.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-054.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-058.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-059.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-062.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-079.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-089.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-090.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-093.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-100.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-101.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-118.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-135.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-142.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-171.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-181.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-193.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-201.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-202.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-216.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-227.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-247.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-267.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-276.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-279.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-280.png" },
  ],
};

/*
Classification log (last run):
  site-001.jpg → warm
  site-002.jpg → neutral
  site-003.webp → vivid
  site-004.jpg → vivid
  site-011.jpg → neutral
  site-012.jpg → neutral
  site-032.jpg → vivid
  site-041.jpg → neutral
  site-042.jpg → neutral
  site-043.jpg → neutral
  site-044.png → neutral
  site-045.jpg → cool
  site-046.jpg → vivid
  site-047.jpg → vivid
  site-048.jpg → cool
  site-049.jpg → neutral
  site-050.jpg → neutral
  site-051.jpg → neutral
  site-052.jpg → neutral
  site-053.jpg → neutral
  site-054.jpg → vivid
  site-055.jpg → cool
  site-056.jpg → cool
  site-057.jpg → cool
  site-058.jpg → vivid
  site-059.png → vivid
  site-060.png → cool
  site-061.jpg → neutral
  site-062.jpg → vivid
  site-063.jpg → neutral
  site-064.jpg → neutral
  site-065.jpg → neutral
  site-066.jpg → neutral
  site-067.jpg → neutral
  site-068.jpg → neutral
  site-069.jpg → neutral
  site-070.jpg → neutral
  site-071.jpg → neutral
  site-072.jpg → neutral
  site-073.jpg → neutral
  site-074.jpg → neutral
  site-075.jpg → neutral
  site-076.jpg → neutral
  site-077.jpg → neutral
  site-078.jpg → neutral
  site-079.jpg → vivid
  site-080.jpg → black
  site-081.jpg → cool
  site-082.jpg → cool
  site-083.jpg → neutral
  site-084.jpg → neutral
  site-085.jpg → neutral
  site-086.jpg → neutral
  site-087.jpg → neutral
  site-088.jpg → neutral
  site-089.jpg → vivid
  site-090.jpg → vivid
  site-093.jpg → vivid
  site-094.jpg → neutral
  site-099.png → neutral
  site-100.jpg → vivid
  site-101.jpg → vivid
  site-118.webp → vivid
  site-120.jpg → neutral
  site-135.png → vivid
  site-142.jpg → vivid
  site-146.jpg → cool
  site-171.jpg → vivid
  site-179.jpg → warm
  site-181.jpg → vivid
  site-187.jpg → neutral
  site-189.jpg → white
  site-193.jpg → vivid
  site-201.jpg → vivid
  site-202.jpg → vivid
  site-209.jpg → cool
  site-210.jpg → warm
  site-211.jpg → warm
  site-216.jpg → vivid
  site-217.jpg → black
  site-226.jpg → neutral
  site-227.jpg → vivid
  site-228.jpg → black
  site-231.jpg → neutral
  site-238.png → neutral
  site-247.png → vivid
  site-259.jpg → neutral
  site-263.jpg → neutral
  site-266.png → warm
  site-267.jpg → vivid
  site-272.jpg → cool
  site-276.jpg → vivid
  site-279.png → vivid
  site-280.png → vivid
  site-281.jpg → black
  site-283.jpg → cool
  site-288.jpg → vivid
  site-293.png → neutral
  site-295.png → neutral
  site-297.png → vivid
  site-299.png → neutral
  site-303.png → vivid
  site-304.png → cool
  site-309.png → neutral
  site-310.jpg → vivid
  site-312.png → neutral
  site-313.png → white
  site-314.png → neutral
  site-315.png → white
  site-317.png → neutral
  site-319.jpg → neutral
  site-321.jpg → neutral
  site-322.png → neutral
  site-323.png → warm
  site-352.jpg → neutral
  site-361.jpg → neutral
  site-363.jpg → neutral
  site-364.jpg → neutral
  site-365.jpg → neutral
  site-366.jpg → neutral
  site-367.jpg → neutral
  site-379.jpg → neutral
  site-380.jpg → vivid
*/
