/**
 * Auto-generated by `npm run color:group` — do not edit by hand.
 * Source: public/images/work/site-pull (see work-person-filtered.json when present; auto palette, no crop).
 * Curation: lib/work-curation.json → applyWorkCuration() in the app.
 * Images analyzed: 352
 * @generated 2026-04-27T16:35:08.919Z
 */

import type { WorkItem } from "./work-types";
import type { WorkColorKey } from "./work-types";

export const workColorGroups: Record<WorkColorKey, WorkItem[]> = {
  black: [
    { kind: "image" as const, src: "/images/work/site-pull/site-080.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-165.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-183.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-199.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-213.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-214.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-217.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-228.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-244.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-246.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-281.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-361.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-359.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-355.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-353.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-352.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-351.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-322.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-321.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-307.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-317.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-297.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-312.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-280.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-302.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-277.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-298.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-274.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-293.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-267.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-290.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-250.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-248.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-243.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-239.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-234.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-227.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-223.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-218.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-208.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-205.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-202.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-196.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-193.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-190.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-186.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-182.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-180.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-175.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-171.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-163.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-157.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-153.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-149.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-144.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-142.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-140.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-137.png" },
  ],
  white: [
    { kind: "image" as const, src: "/images/work/site-pull/site-189.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-308.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-311.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-313.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-315.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-379.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-367.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-366.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-365.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-364.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-363.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-362.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-360.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-356.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-354.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-380.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-325.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-324.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-318.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-320.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-303.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-316.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-288.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-309.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-279.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-301.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-276.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-296.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-273.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-292.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-254.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-270.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-268.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-264.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-262.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-260.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-258.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-256.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-252.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-245.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-238.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-230.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-225.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-215.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-207.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-191.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-185.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-174.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-164.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-159.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-156.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-151.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-139.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-128.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-123.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-110.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-108.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-106.jpg" },
  ],
  neutral: [
    { kind: "image" as const, src: "/images/work/site-pull/site-001.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-002.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-005.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-006-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-006.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-007-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-007.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-008-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-008.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-009-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-009.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-010-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-010.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-011.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-012.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-013.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-014.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-015.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-016.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-017.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-018.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-040.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-041.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-042.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-043.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-044.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-049.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-050.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-051.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-052.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-053.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-061.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-063.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-064.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-065.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-066.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-067.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-068.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-069.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-070.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-071.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-072.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-073.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-074.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-075.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-076.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-077.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-078.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-083.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-084.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-085.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-086.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-087.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-088.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-092.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-094.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-095.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-097.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-098.png" },
  ],
  warm: [
    { kind: "image" as const, src: "/images/work/site-pull/site-091.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-147.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-152.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-170.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-178.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-179.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-204.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-210.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-211.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-220.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-221.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-232.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-266.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-284.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-287.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-289.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-323.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-357.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-358.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-310.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-319.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-300.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-314.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-285.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-305.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-278.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-299.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-275.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-295.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-271.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-291.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-253.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-249.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-247.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-242.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-235.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-233.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-224.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-222.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-216.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-206.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-203.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-201.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-195.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-192.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-188.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-184.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-181.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-176.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-173.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-167.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-162.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-154.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-150.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-145.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-143.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-141.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-138.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-136.png" },
  ],
  cool: [
    { kind: "image" as const, src: "/images/work/site-pull/site-045.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-048.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-055.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-056.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-057.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-060.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-081.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-082.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-096.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-129.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-133.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-146.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-161.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-166.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-168.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-169.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-194.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-197.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-198.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-209.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-229.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-236.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-237.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-241.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-272.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-282.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-283.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-286.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-294.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-304.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-306.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-326.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-269.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-265.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-263.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-261.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-259.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-257.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-255.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-251.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-240.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-231.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-226.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-219.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-212.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-200.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-187.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-177.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-172.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-160.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-158.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-155.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-148.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-132.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-127.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-120.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-109.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-107.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-099.png" },
  ],
  vivid: [
    { kind: "image" as const, src: "/images/work/site-pull/site-003.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-004.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-019-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-019.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-020-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-020.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-021-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-021.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-022-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-022.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-023-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-023.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-024-2.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-024.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-025.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-026-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-026.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-027-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-027.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-028-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-028.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-029.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-030-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-030.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-031-2.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-031.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-032.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-046.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-047.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-054.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-058.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-059.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-062.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-079.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-089.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-090.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-093.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-100.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-101.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-102.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-103.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-104.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-105.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-111.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-112.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-113.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-114.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-115.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-116.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-117.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-118.webp" },
    { kind: "image" as const, src: "/images/work/site-pull/site-119.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-121.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-124.jpg" },
    { kind: "image" as const, src: "/images/work/site-pull/site-126.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-130.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-131.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-134.png" },
    { kind: "image" as const, src: "/images/work/site-pull/site-135.png" },
  ],
};

/*
Classification log (last run):
  site-001.jpg → neutral
  site-002.jpg → neutral
  site-003.webp → vivid
  site-004.jpg → vivid
  site-005.jpg → neutral
  site-006-2.jpg → neutral
  site-006.jpg → neutral
  site-007-2.jpg → neutral
  site-007.jpg → neutral
  site-008-2.jpg → neutral
  site-008.jpg → neutral
  site-009-2.jpg → neutral
  site-009.jpg → neutral
  site-010-2.jpg → neutral
  site-010.jpg → neutral
  site-011.jpg → neutral
  site-012.jpg → neutral
  site-013.jpg → neutral
  site-014.jpg → neutral
  site-015.jpg → neutral
  site-016.jpg → neutral
  site-017.jpg → neutral
  site-018.jpg → neutral
  site-019-2.webp → vivid
  site-019.webp → vivid
  site-020-2.webp → vivid
  site-020.webp → vivid
  site-021-2.webp → vivid
  site-021.webp → vivid
  site-022-2.webp → vivid
  site-022.webp → vivid
  site-023-2.webp → vivid
  site-023.webp → vivid
  site-024-2.webp → vivid
  site-024.webp → vivid
  site-025.webp → vivid
  site-026-2.jpg → vivid
  site-026.jpg → vivid
  site-027-2.jpg → vivid
  site-027.jpg → vivid
  site-028-2.jpg → vivid
  site-028.jpg → vivid
  site-029.jpg → vivid
  site-030-2.jpg → vivid
  site-030.jpg → vivid
  site-031-2.jpg → vivid
  site-031.jpg → vivid
  site-032.jpg → vivid
  site-040.jpg → neutral
  site-041.jpg → neutral
  site-042.jpg → neutral
  site-043.jpg → neutral
  site-044.png → neutral
  site-045.jpg → cool
  site-046.jpg → vivid
  site-047.jpg → vivid
  site-048.jpg → cool
  site-049.jpg → neutral
  site-050.jpg → neutral
  site-051.jpg → neutral
  site-052.jpg → neutral
  site-053.jpg → neutral
  site-054.jpg → vivid
  site-055.jpg → cool
  site-056.jpg → cool
  site-057.jpg → cool
  site-058.jpg → vivid
  site-059.png → vivid
  site-060.png → cool
  site-061.jpg → neutral
  site-062.jpg → vivid
  site-063.jpg → neutral
  site-064.jpg → neutral
  site-065.jpg → neutral
  site-066.jpg → neutral
  site-067.jpg → neutral
  site-068.jpg → neutral
  site-069.jpg → neutral
  site-070.jpg → neutral
  site-071.jpg → neutral
  site-072.jpg → neutral
  site-073.jpg → neutral
  site-074.jpg → neutral
  site-075.jpg → neutral
  site-076.jpg → neutral
  site-077.jpg → neutral
  site-078.jpg → neutral
  site-079.jpg → vivid
  site-080.jpg → black
  site-081.jpg → cool
  site-082.jpg → cool
  site-083.jpg → neutral
  site-084.jpg → neutral
  site-085.jpg → neutral
  site-086.jpg → neutral
  site-087.jpg → neutral
  site-088.jpg → neutral
  site-089.jpg → vivid
  site-090.jpg → vivid
  site-091.jpg → warm
  site-092.jpg → neutral
  site-093.jpg → vivid
  site-094.jpg → neutral
  site-095.jpg → neutral
  site-096.jpg → cool
  site-097.png → neutral
  site-098.png → neutral
  site-099.png → neutral
  site-100.jpg → vivid
  site-101.jpg → vivid
  site-102.jpg → vivid
  site-103.jpg → vivid
  site-104.jpg → vivid
  site-105.jpg → vivid
  site-106.jpg → neutral
  site-107.jpg → neutral
  site-108.jpg → neutral
  site-109.jpg → neutral
  site-110.jpg → neutral
  site-111.jpg → vivid
  site-112.jpg → vivid
  site-113.jpg → vivid
  site-114.jpg → vivid
  site-115.jpg → vivid
  site-116.jpg → vivid
  site-117.jpg → vivid
  site-118.webp → vivid
  site-119.jpg → vivid
  site-120.jpg → neutral
  site-121.jpg → vivid
  site-123.jpg → neutral
  site-124.jpg → vivid
  site-126.png → vivid
  site-127.png → neutral
  site-128.png → neutral
  site-129.png → cool
  site-130.png → vivid
  site-131.png → vivid
  site-132.png → neutral
  site-133.png → cool
  site-134.png → vivid
  site-135.png → vivid
  site-136.png → vivid
  site-137.png → vivid
  site-138.png → vivid
  site-139.png → neutral
  site-140.jpg → vivid
  site-141.jpg → vivid
  site-142.jpg → vivid
  site-143.jpg → vivid
  site-144.png → vivid
  site-145.jpg → vivid
  site-146.jpg → cool
  site-147.jpg → warm
  site-148.jpg → neutral
  site-149.jpg → vivid
  site-150.jpg → vivid
  site-151.jpg → neutral
  site-152.jpg → warm
  site-153.jpg → vivid
  site-154.jpg → vivid
  site-155.jpg → neutral
  site-156.jpg → neutral
  site-157.jpg → vivid
  site-158.jpg → neutral
  site-159.jpg → neutral
  site-160.jpg → neutral
  site-161.jpg → cool
  site-162.jpg → vivid
  site-163.jpg → vivid
  site-164.jpg → neutral
  site-165.jpg → black
  site-166.jpg → cool
  site-167.jpg → vivid
  site-168.jpg → cool
  site-169.jpg → cool
  site-170.png → warm
  site-171.jpg → vivid
  site-172.jpg → neutral
  site-173.jpg → vivid
  site-174.png → neutral
  site-175.jpg → vivid
  site-176.jpg → vivid
  site-177.jpg → neutral
  site-178.jpg → warm
  site-179.jpg → warm
  site-180.jpg → vivid
  site-181.jpg → vivid
  site-182.jpg → vivid
  site-183.jpg → black
  site-184.jpg → vivid
  site-185.jpg → neutral
  site-186.jpg → vivid
  site-187.jpg → neutral
  site-188.jpg → vivid
  site-189.jpg → white
  site-190.jpg → vivid
  site-191.jpg → neutral
  site-192.jpg → vivid
  site-193.jpg → vivid
  site-194.jpg → cool
  site-195.jpg → vivid
  site-196.jpg → vivid
  site-197.jpg → cool
  site-198.jpg → cool
  site-199.jpg → black
  site-200.jpg → neutral
  site-201.jpg → vivid
  site-202.jpg → vivid
  site-203.jpg → vivid
  site-204.jpg → warm
  site-205.jpg → vivid
  site-206.jpg → vivid
  site-207.jpg → neutral
  site-208.jpg → vivid
  site-209.jpg → cool
  site-210.jpg → warm
  site-211.jpg → warm
  site-212.jpg → neutral
  site-213.jpg → black
  site-214.jpg → black
  site-215.jpg → neutral
  site-216.jpg → vivid
  site-217.jpg → black
  site-218.jpg → vivid
  site-219.jpg → neutral
  site-220.jpg → warm
  site-221.jpg → warm
  site-222.jpg → vivid
  site-223.png → vivid
  site-224.jpg → vivid
  site-225.jpg → neutral
  site-226.jpg → neutral
  site-227.jpg → vivid
  site-228.jpg → black
  site-229.jpg → cool
  site-230.png → neutral
  site-231.jpg → neutral
  site-232.jpg → warm
  site-233.jpg → vivid
  site-234.jpg → vivid
  site-235.jpg → vivid
  site-236.jpg → cool
  site-237.jpg → cool
  site-238.png → neutral
  site-239.png → vivid
  site-240.jpg → neutral
  site-241.jpg → cool
  site-242.png → vivid
  site-243.png → vivid
  site-244.png → black
  site-245.png → neutral
  site-246.png → black
  site-247.png → vivid
  site-248.png → vivid
  site-249.png → vivid
  site-250.png → vivid
  site-251.png → neutral
  site-252.jpg → neutral
  site-253.jpg → vivid
  site-254.jpg → vivid
  site-255.jpg → neutral
  site-256.jpg → neutral
  site-257.jpg → neutral
  site-258.jpg → neutral
  site-259.jpg → neutral
  site-260.jpg → neutral
  site-261.jpg → neutral
  site-262.png → neutral
  site-263.jpg → neutral
  site-264.jpg → neutral
  site-265.png → neutral
  site-266.png → warm
  site-267.jpg → vivid
  site-268.jpg → neutral
  site-269.jpg → neutral
  site-270.jpg → neutral
  site-271.jpg → vivid
  site-272.jpg → cool
  site-273.jpg → vivid
  site-274.jpg → vivid
  site-275.jpg → vivid
  site-276.jpg → vivid
  site-277.jpg → vivid
  site-278.jpg → vivid
  site-279.png → vivid
  site-280.png → vivid
  site-281.jpg → black
  site-282.jpg → cool
  site-283.jpg → cool
  site-284.jpg → warm
  site-285.jpg → vivid
  site-286.jpg → cool
  site-287.jpg → warm
  site-288.jpg → vivid
  site-289.jpg → warm
  site-290.jpg → neutral
  site-291.jpg → neutral
  site-292.jpg → neutral
  site-293.png → neutral
  site-294.png → cool
  site-295.png → neutral
  site-296.png → neutral
  site-297.png → vivid
  site-298.png → neutral
  site-299.png → neutral
  site-300.png → vivid
  site-301.png → neutral
  site-302.jpg → neutral
  site-303.png → vivid
  site-304.png → cool
  site-305.jpg → neutral
  site-306.jpg → cool
  site-307.jpg → vivid
  site-308.png → white
  site-309.png → neutral
  site-310.jpg → vivid
  site-311.png → white
  site-312.png → neutral
  site-313.png → white
  site-314.png → neutral
  site-315.png → white
  site-316.png → neutral
  site-317.png → neutral
  site-318.jpg → vivid
  site-319.jpg → neutral
  site-320.jpg → neutral
  site-321.jpg → neutral
  site-322.png → neutral
  site-323.png → warm
  site-324.png → vivid
  site-325.png → vivid
  site-326.png → cool
  site-351.jpg → neutral
  site-352.jpg → neutral
  site-353.jpg → neutral
  site-354.jpg → neutral
  site-355.jpg → neutral
  site-356.jpg → neutral
  site-357.jpg → warm
  site-358.jpg → warm
  site-359.jpg → neutral
  site-360.jpg → neutral
  site-361.jpg → neutral
  site-362.jpg → neutral
  site-363.jpg → neutral
  site-364.jpg → neutral
  site-365.jpg → neutral
  site-366.jpg → neutral
  site-367.jpg → neutral
  site-379.jpg → neutral
  site-380.jpg → vivid
*/
